main: com.cavetale.tetris.TetrisPlugin

name: Tetris
version: 0.1
description: Tetris Plugin
api-version: 1.17

author: StarTux
website: https://github.com/StarTux/Tetris

depend: [Core, Mytems, Area, Sidebar, WorldMarker]
softdepend: []

commands:

  tetris:
    aliases: []
    description: Tetris Command
    permission: tetris.tetris
    usage: |-
      /tetris

permissions:

  tetris.tetris:
    description: Use /tetris
    default: op
