main: com.cavetale.tetris.TetrisPlugin
name: Tetris

version: 0.1
api-version: 1.18

description: Tetris Minigame
author: StarTux
website: https://github.com/StarTux/Tetris

depend: [Core, SQL, PlayerCache, Mytems, Area, Sidebar, WorldMarker, Fam]
softdepend: []

commands:

  tetris:
    aliases: []
    description: Tetris Command
    permission: tetris.tetris
    usage: |-
      /tetris

  tetrisadmin:
    aliases: [tetrisadm]
    description: Admin Command
    permission: tetris.admin
    usage: |-
      /tetrisadmin

permissions:

  tetris.tetris:
    description: Use /tetris
    default: op

  tetris.admin:
    description: Use /tetrisadmin
    default: op
